# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  shellcheck:
    docker:
      - image: public.ecr.aws/debian/debian:11
    steps:
      - run:
          name: "Install dependencies"
          command: "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install shellcheck git ssh-client"
      - checkout
      - run:
          name: "shellcheck"
          command: "shellcheck -s bash -S warning ec2-metadata ec2nvme-nsid ec2udev-vbd"
  code-checks-al2022:
    docker:
      - image: public.ecr.aws/amazonlinux/amazonlinux:2022
    steps:
      - run:
          name: "Install dependencies"
          command: |
            dnf -y install python3-pip git
            pip install flake8
      - checkout
      - run:
          name: "flake8"
          command: "git grep -l '^#!/usr/bin/env python' | xargs flake8 ebsnvme-id"

  build-al2022-rpm:
    docker:
      - image: public.ecr.aws/amazonlinux/amazonlinux:2022
    steps:
      - run:
          name: "Install dependencies"
          command: |
            dnf -y install rpm-build git python3 python3-devel systemd-rpm-macros
      - checkout
      - run:
          name: "rpmbuild"
          command: |
            rpmbuild --define "_sourcedir $PWD" -bb amazon-ec2-utils.spec

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci-workflow:
    jobs:
      - shellcheck
      - code-checks-al2022
      - build-al2022-rpm
