# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  code-checks-al2:
    docker:
      - image: public.ecr.aws/amazonlinux/amazonlinux:2
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            yum -y install python-pip git
            pip install flake8
      - run:
          name: "flake8"
          command: "git grep -l '^#!/usr/bin/env python' | xargs flake8 ebsnvme-id"

  build-al2-rpm:
    docker:
      - image: public.ecr.aws/amazonlinux/amazonlinux:2
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            yum -y install rpm-build python
      - run:
          name: "rpmbuild"
          command: "rpmbuild --define \"_sourcedir $PWD\" -bb amazon-ec2-utils.spec"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci-workflow:
    jobs:
      - code-checks-al2
      - build-al2-rpm
